# Default test configuration. Do not store production credentials here.
# For CI or local overrides, set environment variables as described in README.md
base_url: "http://localhost:8000"
auth:
  username: ""
  password: ""
defaults:
  timeout: 10
# Set to false for local dev with self-signed certs
verify_ssl: false
